In [39]:
from pysentimiento import create_analyzer

In [40]:
model_analyser_sent = create_analyzer(task="sentiment", lang="pt")

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12828.57it/s]

In [41]:
phrase1 = "Eu amei o livro que você me recomendou!"
phrase2 = "Acabei pegando uma chuva antes de chegar em casa!"
phrase3 = "Hoje o clima está nublado, mas não choveu"
phrase4 = "O trânsito estava horrível, péssimo e deplorável, por isso cheguei atrasado em meu compromisso e acabei perdendo todo o dinheiro referente aquele contrato"
phrase5 = "É impressionante a sua capacidade de me irritar!"
phrase6 = "É impressionante a sua capacidade de me acordar!"

In [42]:
model_analyser_sent.predict(phrase1)

AnalyzerOutput(output=POS, probas={POS: 0.991, NEU: 0.006, NEG: 0.002})

In [43]:
model_analyser_sent.predict(phrase2)

AnalyzerOutput(output=NEG, probas={NEG: 0.604, NEU: 0.359, POS: 0.037})

In [44]:
model_analyser_sent.predict(phrase3)

AnalyzerOutput(output=NEU, probas={NEU: 0.839, POS: 0.094, NEG: 0.067})

In [45]:
model_analyser_sent.predict(phrase4)

AnalyzerOutput(output=NEG, probas={NEG: 0.991, NEU: 0.006, POS: 0.003})

In [46]:
model_analyser_sent.predict(phrase5)

AnalyzerOutput(output=NEG, probas={NEG: 0.881, NEU: 0.082, POS: 0.037})

In [47]:
model_analyser_sent.predict(phrase6)

AnalyzerOutput(output=NEU, probas={NEU: 0.492, POS: 0.384, NEG: 0.124})

In [48]:
import pandas as pd

In [49]:
dataframe = pd.read_csv("dados/frases.csv")

In [50]:
dataframe

    ID                                              Frase
0    1  Eu amei demais esse produto mudou completament...
1    2                     O pacote chegou ontem de tarde
2    3  Esse foi o pior atendimento que já recebi na vida
3    4  Estou muito feliz com os resultados superou to...
4    5         A reunião está marcada para segunda às 10h
5    6  Odeio ficar esperando em filas longas é muito ...
6    7  Que filme incrível assisti duas vezes e ainda ...
7    8                    O documento foi atualizado hoje
8    9  Estou muito decepcionado com o serviço ao cliente
9   10         Hoje foi um dia maravilhoso tudo deu certo
10  11                                A loja fecha às 21h
11  12  Essa comida tem um gosto horrível jamais vou p...
12  13   Me sinto muito grato por todo o apoio que recebi
13  14                       O arquivo tem 4MB de tamanho
14  15  Não acredito como o funcionário foi grosseiro ...
15  16  Que pôr do sol lindo me sinto muito tranquilo ...
16  17                        O relatório tem três seções
17  18  Me arrependo de ter comprado isso quebrou no p...
18  19  Minha equipe fez um trabalho incrível estou mu...
19  20             A temperatura lá fora está em 22 graus
20  21  Esse aplicativo trava o tempo todo é insuportável
21  22  Me diverti muito nessa viagem foi a melhor da ...
22  23                            A lista tem cinco itens
23  24  O barulho da obra é insuportável não consigo m...
24  25  Acabei de ser promovido estou nas nuvens de fe...
25  26        A reunião foi transferida para quinta-feira
26  27  Me sinto muito decepcionado com essa empresa p...
27  28  Esse é sem dúvida o melhor café que já tomei n...
28  29                   O sistema será atualizado amanhã
29  30  Estou exausto e estressado não aguento mais es...

In [51]:
dataframe.head()

   ID                                              Frase
0   1  Eu amei demais esse produto mudou completament...
1   2                     O pacote chegou ontem de tarde
2   3  Esse foi o pior atendimento que já recebi na vida
3   4  Estou muito feliz com os resultados superou to...
4   5         A reunião está marcada para segunda às 10h

In [52]:
dataframe.tail()

    ID                                              Frase
25  26        A reunião foi transferida para quinta-feira
26  27  Me sinto muito decepcionado com essa empresa p...
27  28  Esse é sem dúvida o melhor café que já tomei n...
28  29                   O sistema será atualizado amanhã
29  30  Estou exausto e estressado não aguento mais es...

In [53]:
dataframe["Frase"]

0     Eu amei demais esse produto mudou completament...
1                        O pacote chegou ontem de tarde
2     Esse foi o pior atendimento que já recebi na vida
3     Estou muito feliz com os resultados superou to...
4            A reunião está marcada para segunda às 10h
5     Odeio ficar esperando em filas longas é muito ...
6     Que filme incrível assisti duas vezes e ainda ...
7                       O documento foi atualizado hoje
8     Estou muito decepcionado com o serviço ao cliente
9            Hoje foi um dia maravilhoso tudo deu certo
10                                  A loja fecha às 21h
11    Essa comida tem um gosto horrível jamais vou p...
12     Me sinto muito grato por todo o apoio que recebi
13                         O arquivo tem 4MB de tamanho
14    Não acredito como o funcionário foi grosseiro ...
15    Que pôr do sol lindo me sinto muito tranquilo ...
16                          O relatório tem três seções
17    Me arrependo de ter comprado isso quebrou no p...
18    Minha equipe fez um trabalho incrível estou mu...
19               A temperatura lá fora está em 22 graus
20    Esse aplicativo trava o tempo todo é insuportável
21    Me diverti muito nessa viagem foi a melhor da ...
22                              A lista tem cinco itens
23    O barulho da obra é insuportável não consigo m...
24    Acabei de ser promovido estou nas nuvens de fe...
25          A reunião foi transferida para quinta-feira
26    Me sinto muito decepcionado com essa empresa p...
27    Esse é sem dúvida o melhor café que já tomei n...
28                     O sistema será atualizado amanhã
29    Estou exausto e estressado não aguento mais es...
Name: Frase, dtype: str

In [55]:
prev_result = model_analyser_sent.predict(dataframe["Frase"])
prev_result

Map: 100%|██████████| 30/30 [00:00<00:00, 2550.30 examples/s]
c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

[AnalyzerOutput(output=POS, probas={POS: 0.992, NEU: 0.006, NEG: 0.002}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.936, NEG: 0.037, POS: 0.027}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.988, NEU: 0.008, POS: 0.004}),
 AnalyzerOutput(output=POS, probas={POS: 0.983, NEU: 0.014, NEG: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.954, POS: 0.027, NEG: 0.019}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.978, NEU: 0.013, POS: 0.009}),
 AnalyzerOutput(output=POS, probas={POS: 0.990, NEU: 0.008, NEG: 0.002}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.957, POS: 0.028, NEG: 0.016}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.991, NEU: 0.005, POS: 0.003}),
 AnalyzerOutput(output=POS, probas={POS: 0.987, NEU: 0.010, NEG: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.953, POS: 0.025, NEG: 0.023}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.989, NEU: 0.008, POS: 0.003}),
 AnalyzerOutput(output=POS, probas={POS: 0.973, NEU: 0.024, NEG: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.931, NEG: 0.048, POS: 0.021}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.992, NEU: 0.005, POS: 0.003}),
 AnalyzerOutput(output=POS, probas={POS: 0.988, NEU: 0.009, NEG: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.961, NEG: 0.025, POS: 0.014}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.986, NEU: 0.010, POS: 0.004}),
 AnalyzerOutput(output=POS, probas={POS: 0.987, NEU: 0.011, NEG: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.914, NEG: 0.063, POS: 0.023}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.990, POS: 0.005, NEU: 0.004}),
 AnalyzerOutput(output=POS, probas={POS: 0.989, NEU: 0.008, NEG: 0.002}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.944, POS: 0.040, NEG: 0.016}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.988, NEU: 0.007, POS: 0.005}),
 AnalyzerOutput(output=POS, probas={POS: 0.963, NEU: 0.032, NEG: 0.005}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.953, NEG: 0.026, POS: 0.021}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.992, NEU: 0.005, POS: 0.003}),
 AnalyzerOutput(output=POS, probas={POS: 0.981, NEU: 0.015, NEG: 0.004}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.962, POS: 0.023, NEG: 0.015}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.987, NEU: 0.008, POS: 0.006})]

In [60]:
sentiment = []
for result in prev_result:
    sentiment.append(result.output)
    
sentiment

['POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG',
 'POS',
 'NEU',
 'NEG']

In [ ]:
dataframe["Sentimento"] = sentiment